# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IsoIGN
                                 A QGIS plugin
 Extraction de zone de chalandises depuis l'API géoportail de l'IGN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-20
        copyright            : (C) 2020 by T.Jacquemot
        email                : t.jacquemot@inddigo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IsoIGN class from file IsoIGN.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .iso_ign import IsoIGN

    return IsoIGN(iface)
