# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IsoIGNDialog
                                 A QGIS plugin
 Extraction de zone de chalandises et calcul d'itinéraires depuis l'API itineraire.ign.fr
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2022 by T.Jacquemot
        email                : t.jacquemot@inddigo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtCore import Qt
from pathlib import Path


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer


class IsoIGNDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        uifile = Path(__file__).parent / "iso_ign_dialog_base.ui"
        self.setWindowFlags(Qt.WindowStaysOnTopHint)
        uic.loadUi(str(uifile), self)

        ori_map_layer_combo_box = self.orily_picker
        ori_field_combo_box = self.orifield_picker
        ori_field_combo_box.setLayer(ori_map_layer_combo_box.currentLayer())
        ori_map_layer_combo_box.layerChanged.connect(ori_field_combo_box.setLayer)

        self.destfield_picker.setLayer(self.destly_picker.currentLayer())
        self.destly_picker.layerChanged.connect(self.destfield_picker.setLayer)
